# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MSU*SEL
tagline:          'Montana State University Software Engineering Labs'
description:      'Welcome to Montana State University Software Engineering Labs'
url:              https://msusel.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MSUSEL
