# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-redirect-from

# Permalinks
permalink:        pretty

# Setup
title:            MSU*SEL
tagline:          'Montana State University Software Engineering Labs'
description:      'Welcome to Montana State University Software Engineering Labs'
url:              https://MSUSEL.github.io
baseurl:          /

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/MSUSEL/MSUSEL.github.io
